USE SnapPex;
GO

CREATE TABLE MACHINE (
	MachineNr INT IDENTITY(1,1) PRIMARY KEY,
	MachineStatus INT NOT NULL
);
GO

CREATE TABLE COMPONENT(
	ComponentName NVARCHAR(50) PRIMARY KEY,
	AmountPerMachine INT NOT NULL,
	AmountInStock INT NOT NULL,
	ImagePath NVARCHAR(255)
);
GO

CREATE TABLE SCREW(
	RingClipSize INT PRIMARY KEY,
	AmountInStock INT NOT NULL
);
GO

CREATE TABLE RENTAL(
	RentalID INT IDENTITY(1,1) PRIMARY KEY,
	CompanyName NVARCHAR(100) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE
);
GO

CREATE TABLE MACHINE_RENTAL(
	MachineNr INT,
	RentalID INT,
	PRIMARY KEY (MachineNr, RentalID),

	CONSTRAINT FK_MACHINE_RENTAL_MACHINE
		FOREIGN KEY (MachineNr)
		REFERENCES MACHINE(MachineNr),

	CONSTRAINT FK_MACHINE_RENTAL_RENTAL
		FOREIGN KEY (RentalID)
		REFERENCES RENTAL(RentalID)
);

